version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: pytest -s -v
    depends_on:
      - db_test


  db_test:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    user: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env_test
    ports:
      - "5433:5433"

volumes:
  dbdata: