version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - db
    restart: on-failure


  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    user: postgres
    volumes:
     - dbdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - mynetwork



networks:
  mynetwork:


volumes:
  dbdata: