version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: pytest -s -v
    networks:
      - mynetwork
networks:
  mynetwork:

